# Generated by Django 4.1.3 on 2022-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Funcionario')),
                ('cpf', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('rua', models.CharField(blank=True, max_length=16, null=True, verbose_name='Rua')),
                ('cidade', models.CharField(blank=True, max_length=16, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=16, null=True, verbose_name='Bairro')),
                ('numero_casa', models.IntegerField(blank=True, null=True, verbose_name='Numero da Casa')),
                ('email', models.CharField(blank=True, max_length=16, null=True, verbose_name='Email')),
                ('senha', models.CharField(blank=True, max_length=16, null=True, verbose_name='Senha')),
                ('nivel', models.CharField(choices=[('Funcionario', 'Funcionario'), ('Gerente', 'Gerente')], max_length=100, null=True, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
