# Generated by Django 4.1.3 on 2022-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'imovel',
                'verbose_name_plural': 'imoveis',
            },
        ),
    ]
