# Generated by Django 4.1.3 on 2022-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('Alugar', 'Alugar'), ('Vender', 'Vender')], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
