# Generated by Django 4.1.3 on 2022-11-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Predio comercial', 'Predio comercial')], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
