# Generated by Django 4.1.3 on 2022-11-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem',
            field=models.ManyToManyField(to='imoveis.imagemimovel'),
        ),
    ]
