# Generated by Django 4.1.3 on 2022-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imagemimovel_imovel_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='imagem',
        ),
        migrations.DeleteModel(
            name='ImagemImovel',
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
