# Generated by Django 4.1.3 on 2022-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_remove_imovel_imagem_delete_imagemimovel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do imovel'),
        ),
    ]
