# Generated by Django 4.1.3 on 2022-11-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venda', 'Venda'), ('Aluga', 'Aluga')], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
