# Generated by Django 4.1.3 on 2022-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pagamento_items_pagamento_total_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempagamento',
            name='data_vencimento',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
