# Generated by Django 4.1.3 on 2022-11-23 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0005_pagamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
