# Generated by Django 4.1.3 on 2022-11-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_casa',
            field=models.IntegerField(blank=True, default=75, null=True, verbose_name='Numero da Casa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
