# Generated by Django 4.1.3 on 2022-11-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_bairro_cliente_cidade_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_casa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero da Casa'),
        ),
    ]
